spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://database/distributed
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 1GB
#server:
#  port: 9000
